### ISSUE TITLE
Research and choose bot from Hubot, Lita, Cog, etc.

### ISSUE THREAD

**Issue by AE637** [AE637/CIT-481-BOT#4]
Research and choose bot from Hubot, Lita, Cog, etc.

**Comment by ErikBlomquist** [comment]
StackStorm + Hubot seems to be the best option.

**Comment by AE637** [comment]
I agree on Hubot, seems like its a good bet.

**Comment by AE637** [comment]
We will be going with Hubot, closing issue!
